export const subjects = [
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117822',
        ZKRATKA: 'CJ',
        NAZEV: 'Český jazyk',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 1,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119626',
        ZKRATKA: 'CJL',
        NAZEV: 'Český jazyk a literatura',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 1,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117679',
        ZKRATKA: 'AJ',
        NAZEV: 'Anglický jazyk',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 2,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117833',
        ZKRATKA: 'NJ',
        NAZEV: 'Německý jazyk',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 3,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119673',
        ZKRATKA: 'FJ',
        NAZEV: 'Francouzský jazyk',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 4,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117836',
        ZKRATKA: 'SJ',
        NAZEV: 'Španělský jazyk',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 5,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119684',
        ZKRATKA: 'RJ',
        NAZEV: 'Ruský  jazyk',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 6,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119690',
        ZKRATKA: 'LA',
        NAZEV: 'Latina',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 7,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119627',
        ZKRATKA: 'OV',
        NAZEV: 'Občanská výchova',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 8,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117682',
        ZKRATKA: 'ZSV',
        NAZEV: 'Základy společenských věd',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 9,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117683',
        ZKRATKA: 'DE',
        NAZEV: 'Dějepis',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 10,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119637',
        ZKRATKA: 'ZE',
        NAZEV: 'Zeměpis',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 11,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117816',
        ZKRATKA: 'PRV',
        NAZEV: 'Prvouka',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 12,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119591',
        ZKRATKA: 'MA',
        NAZEV: 'Matematika',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 13,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117686',
        ZKRATKA: 'FY',
        NAZEV: 'Fyzika',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 14,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119629',
        ZKRATKA: 'CH',
        NAZEV: 'Chemie',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 15,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119622',
        ZKRATKA: 'BI',
        NAZEV: 'Biologie',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 16,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119564',
        ZKRATKA: 'IVT',
        NAZEV: 'Informatika a výpočetní technika',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 17,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117825',
        ZKRATKA: 'HV',
        NAZEV: 'Hudební výchova',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 18,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119649',
        ZKRATKA: 'HVM',
        NAZEV: 'Hudební výchova s metodikou',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 19,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119650',
        ZKRATKA: 'VVM',
        NAZEV: 'Výtvarná výchova s metodikou',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 20,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119648',
        ZKRATKA: 'TVM',
        NAZEV: 'Tělesná výchova s metodikou',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 21,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119606',
        ZKRATKA: 'POZ',
        NAZEV: 'Péče o zdraví',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 22,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119631',
        ZKRATKA: 'VV',
        NAZEV: 'Výtvarná výchova',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 23,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117827',
        ZKRATKA: 'PČ',
        NAZEV: 'Pracovní činnosti',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 24,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117664',
        ZKRATKA: 'EV',
        NAZEV: 'Estetická výchova',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 25,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'C131154',
        ZKRATKA: 'EVH',
        NAZEV: 'Estetická výchova - hudební obor',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 25,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'C131155',
        ZKRATKA: 'EVV',
        NAZEV: 'Estetická výchova – výtvarný obor',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 25,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117692',
        ZKRATKA: 'TV',
        NAZEV: 'Tělesná výchova',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 26,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117694',
        ZKRATKA: 'VKZ',
        NAZEV: 'Výchova ke zdraví',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 27,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'C174441',
        ZKRATKA: 'PP',
        NAZEV: 'Přírodovědné praktikum',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 27,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119641',
        ZKRATKA: 'PED',
        NAZEV: 'Pedagogika',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 28,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119590',
        ZKRATKA: 'PSY',
        NAZEV: 'Psychologie',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 29,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119647',
        ZKRATKA: 'DVM',
        NAZEV: 'Dramatická výchova s metodikou',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 30,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119643',
        ZKRATKA: 'PV',
        NAZEV: 'Pohybová výchova',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 31,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119644',
        ZKRATKA: 'HHN',
        NAZEV: 'Hra na hudební nástroj',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 32,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119645',
        ZKRATKA: 'LJP',
        NAZEV: 'Literární a jazykové praktikum',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 33,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119646',
        ZKRATKA: 'UPP',
        NAZEV: 'Učební pedagogická praxe',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 34,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119662',
        ZKRATKA: 'SDV',
        NAZEV: 'Seminář z dramatické výchovy',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 36,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119566',
        ZKRATKA: 'SSV',
        NAZEV: 'Seminář ze základů společenských věd',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 36,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119613',
        ZKRATKA: 'STV',
        NAZEV: 'Seminář z tělesné výchovy',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 37,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119664',
        ZKRATKA: 'SHV',
        NAZEV: 'Seminář z hudební výchovy',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 39,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119667',
        ZKRATKA: 'KA',
        NAZEV: 'Konverzace v anglickém jazyce',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 40,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117673',
        ZKRATKA: 'KN',
        NAZEV: 'Konverzace v německém jazyce',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 41,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117711',
        ZKRATKA: 'KF',
        NAZEV: 'Konverzace ve  francouzském jazyce',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 42,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117723',
        ZKRATKA: 'KS',
        NAZEV: 'Konverzace ve španělském jazyce',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 43,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E124961',
        ZKRATKA: 'KR',
        NAZEV: 'Konverzace v  ruském jazyce',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 44,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119666',
        ZKRATKA: 'RA',
        NAZEV: 'Reálie anglicky mluvících zemí',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 45,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119655',
        ZKRATKA: 'RN',
        NAZEV: 'Reálie německy mluvících zemí',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 46,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E124962',
        ZKRATKA: 'SVV',
        NAZEV: 'Seminář z výtvarné výchovy',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 48,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119569',
        ZKRATKA: 'SD',
        NAZEV: 'Seminář z dějepisu',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 49,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117654',
        ZKRATKA: 'SZ',
        NAZEV: 'Seminář ze zeměpisu',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 50,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119568',
        ZKRATKA: 'SM',
        NAZEV: 'Seminář  z matematiky',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 51,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117675',
        ZKRATKA: 'SDG',
        NAZEV: 'Seminář z deskriptivní geometrie',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 52,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119597',
        ZKRATKA: 'SF',
        NAZEV: 'Seminář  z fyziky',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 53,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119598',
        ZKRATKA: 'SCH',
        NAZEV: 'Seminář z chemie',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 54,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119599',
        ZKRATKA: 'SB',
        NAZEV: 'Seminář z biologie',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 55,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117659',
        ZKRATKA: 'PRO',
        NAZEV: 'Programování',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 56,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'C131156',
        ZKRATKA: 'SIP',
        NAZEV: 'Seminář z informatiky a programování',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 56,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119601',
        ZKRATKA: 'SI',
        NAZEV: 'Seminář z informatiy',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 57,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117676',
        ZKRATKA: 'DU',
        NAZEV: 'Dějiny umění',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 59,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119659',
        ZKRATKA: 'SEV',
        NAZEV: 'Seminář z estetické výchovy',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 60,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117649',
        ZKRATKA: 'LS',
        NAZEV: 'Literární seminář',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 64,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117727',
        ZKRATKA: 'SL',
        NAZEV: 'Seminář z latiny',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 65,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117819',
        ZKRATKA: 'PŘI',
        NAZEV: 'Přírodověda',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 70,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117829',
        ZKRATKA: 'VLA',
        NAZEV: 'Vlastivěda',
        PRIZNAK_DRUH_PREDMETU: 'P',
        PORADI_ZOBRAZENI: 72,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117821',
        ZKRATKA: 'ac',
        NAZEV: 'Anglické cvičení',
        PRIZNAK_DRUH_PREDMETU: 'N',
        PORADI_ZOBRAZENI: 76,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E117832',
        ZKRATKA: 'aj',
        NAZEV: 'Anglický jazyk - N',
        PRIZNAK_DRUH_PREDMETU: 'N',
        PORADI_ZOBRAZENI: 80,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119681',
        ZKRATKA: 'nj',
        NAZEV: 'Německý jazyk',
        PRIZNAK_DRUH_PREDMETU: 'N',
        PORADI_ZOBRAZENI: 81,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119685',
        ZKRATKA: 'sj',
        NAZEV: 'Španělský jazyk',
        PRIZNAK_DRUH_PREDMETU: 'N',
        PORADI_ZOBRAZENI: 82,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'E119624',
        ZKRATKA: 'PPZ',
        NAZEV: 'Pedagogicko-psychologický základ',
        PRIZNAK_DRUH_PREDMETU: null,
        PORADI_ZOBRAZENI: 85,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'C134275',
        ZKRATKA: 'D20',
        NAZEV: 'Dějiny 20. století',
        PRIZNAK_DRUH_PREDMETU: 'N',
        PORADI_ZOBRAZENI: 86,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'C135844',
        ZKRATKA: 'sz',
        NAZEV: 'Sborový zpěv',
        PRIZNAK_DRUH_PREDMETU: 'N',
        PORADI_ZOBRAZENI: 90,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'C156830',
        ZKRATKA: 'ch',
        NAZEV: 'Chemie - N',
        PRIZNAK_DRUH_PREDMETU: 'N',
        PORADI_ZOBRAZENI: 95,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'C172097',
        ZKRATKA: 'CM',
        NAZEV: 'Cvičení z matematiky',
        PRIZNAK_DRUH_PREDMETU: 'V',
        PORADI_ZOBRAZENI: 98,
    },
    {
        SKOLNI_ROK_ID: 'C13884',
        PREDMET_ID: 'C172096',
        ZKRATKA: 'CCJ',
        NAZEV: 'Cvičení z českého jazyka',
        PRIZNAK_DRUH_PREDMETU: 'N',
        PORADI_ZOBRAZENI: 100,
    },
]
